Ahorcado
a10pepo/EDEM_MDA2324 pull request #112
Opened 2023-10-27 18:23 UTC by rafapm21

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-10-27 20:15 UTC, a10pepo requested changes

2023-10-27 20:15 UTC, a10pepo commented on Alumnos/FS/RAFAEL-PEREZ-MORALES/LINUX/Ejercicio-Script/script.sh
> +
Falta la cabecera del script

2023-11-11 16:52 UTC, alhercan approved these changes
Buen trabajo!
Una recomendación, si en lugar de CMD usas entry point te simplicaria el comando de invocar al script pudiendo poner simplemente docker run <image_id> 4 5

2023-11-21 21:10 UTC, a10pepo commented
@rafapm21  sigue sin estar el cambio en el fichero script...

2024-01-02 07:47 UTC, merged