Ahorcado
a10pepo/EDEM_MDA2324 pull request #114
Opened 2023-10-27 18:31 UTC by jesusjrnt

Ahorcado

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-10-27 20:13 UTC, a10pepo requested changes

2023-10-27 20:13 UTC, a10pepo commented on Alumnos/FS/Jesus Jornet Orti/Ahorcado/dockerfile
> +ENTRYPOINT [ python , /Users/jesus/Documents/GitHub/EDEM_MDA2324/Alumnos/FS/Jesus Jornet Orti/Ahorcado/Ahorcado.py ]
Aqui tienes que poner la ruta local de tu archivo, no la de tu ordenador... piensa que esto es un ordenador virtual nuevo.

ENTRYPOINT [ "python", "./Ahorcado.py" ]

2023-11-13 07:48 UTC, martinImagina approved these changes
Faltan algunos retos por resolver, pero los que están, están bien :)

2023-11-21 21:12 UTC, a10pepo commented
@jesusjrnt los cambios siguen sin hacer.. ¯\_(ツ)_/¯

2024-01-13 14:22 UTC, a10pepo approved these changes

2024-01-13 14:22 UTC, merged