cambios 2
a10pepo/EDEM_MDA2324 pull request #150
Opened 2023-11-09 15:41 UTC by mapova

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-11-13 07:50 UTC, martinImagina commented on Alumnos/FS/MAR-PONS-VALVERDE/ejercicios_python/SESION 1/ejercicio2.py
no es necesario poner el str() para definir una cadena de texto :)

simplemente usa:

nombre = "Mar"
print('Hola', nombre)

o también podrías emplear

print(f'Hola, {nombre}')

2023-11-13 07:54 UTC, martinImagina requested changes
He puesto algunos comentarios en ejercicios entregable sde Pytgon para que los puedas revisar @mapova :D. Inténtalo durante esta semana y vuelve a subirlos para que te lo pueda aprobar todo :)

¡Un saludo!

2023-11-13 07:54 UTC, martinImagina commented on Alumnos/FS/MAR-PONS-VALVERDE/ejercicios_python/SESION 3/ejercicio1.py
La variable saludo no la estás empleando.

tal vez, si quieres que se muestre por consola puedes hacer un print o incluirlo en el input donde solicitas las opciones.

Además, una vez muestras las opciones, debería realizar algo el programa. Es decir, deberías escoger el 1 y entonces pedirte las opciones de inversión. Si selecciona la X, debería cerrarse el programa (por ejemplo, empleando exit())


Te lo dejo aquí comentada por si quieres rehacerlo :)

2023-11-20 08:18 UTC, martinImagina commented on Alumnos/FS/MAR-PONS-VALVERDE/ejercicios_python/SESION 4/ejercicio2.py
Me resulta curioso que hayas empleado Flask. Bien es cierto que lo mencionamos en el curso, pero no llegamos a emplearlo.

Muy intersante :) Como verás, lo que has montado es una apliacción web con una ruta "/" que cuando lo ejecutas en tu equipo, podrás acceder vía Navegador o herramientas como Postman y ahí se verá el texto "¡Hola, Mundo!", pero podría devolver un HTML, un JSON, etc.

Por lo que si te interesa crear aplicaciones Web con Python, te recomiendo seguir investigando con Flask :)

2023-11-20 08:19 UTC, martinImagina commented on Alumnos/FS/MAR-PONS-VALVERDE/ejercicios_python/SESION 4/ejercicio3.py
Muy bien :)

2023-11-20 08:19 UTC, martinImagina approved these changes
Buen trabajo :)

2023-11-21 21:13 UTC, a10pepo approved these changes

2023-11-21 21:13 UTC, merged