Chuck Norris
a10pepo/EDEM_MDA2324 pull request #192
Opened 2023-11-16 11:19 UTC by Josanrc

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [X] He probado mi código y funciona en local
- [X] He validado que mi código es correcto a niveles de formato
- [X] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [X] No he copiado mi código porque soy una persona muy responsable :-), **pero si he utilizado diversas fuentes**

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-11-16 17:20 UTC, a10pepo requested changes

2023-11-16 17:20 UTC, a10pepo commented on ChuckCasa.txt
Este fichero está fuera de tu carpeta

2023-11-16 17:20 UTC, a10pepo commented on EjercicioRepasoClase091123.ipynb
Este fichero está fuera de tu carpeta

2023-11-16 17:20 UTC, a10pepo commented on index.html
Este fichero esta fuera de tu carpeta

2023-11-17 04:05 UTC, Josanrc commented on ChuckCasa.txt
Arreglado Sorry!

2023-11-17 04:06 UTC, Josanrc commented on EjercicioRepasoClase091123.ipynb
Arreglado Sorry!

2023-11-21 21:16 UTC, a10pepo approved these changes

2023-11-21 21:17 UTC, merged

2023-11-21 21:17 UTC, a10pepo commented
Muy bien Josan, has arreglado errores, seguido la pr GRAN TRABAJO!