add notebooks
a10pepo/EDEM_MDA2324 pull request #195
Opened 2023-11-16 20:08 UTC by StasKorotchenko

notebooks archivo

2023-11-18 08:10 UTC, a10pepo commented
Stas si mergeo esto, te va a borrar contenido de main.. no es lo mismo que no esté en la Rama a que esté marcado para borrar. ¿Me explico?

2023-11-18 08:11 UTC, a10pepo requested changes
tienes que tener todo lo qeu quieres mantener, o se borrarán los ficheros en main

2023-11-18 15:16 UTC, StasKorotchenko commented
En realidad, no entendí completamente a qué te referías. Pero tengo todos los archivos localmente en mi computadora.

2023-11-21 21:18 UTC, a10pepo commented
Cerremos esta PR y empiezas otra vez con tu local

2023-11-21 21:18 UTC, closed without merging