Notebooks Análisis por GC
a10pepo/EDEM_MDA2324 pull request #219
Opened 2023-11-21 21:24 UTC by StasKorotchenko

# PULL REQUEST

new PR

2023-11-26 22:59 UTC, a10pepo requested changes

2023-11-26 22:59 UTC, a10pepo commented on Alumnos/FS/Stas Korotchenko/SQL/sql_stas.sql
Si te apruebo esto... vas a borrar ficheros de main de tus entregables!!

2023-11-27 19:07 UTC, StasKorotchenko commented
Debo cancelar la eliminación de otros archivos?

2023-11-27 19:08 UTC, pedronieto1206 commented
Si, te recomiendo que empieces de una rama nueva actualizada de main y hagas una pr solo con tus archivos nuevos

2023-11-28 21:38 UTC, closed without merging