Entregables 1, 2, 3
a10pepo/EDEM_MDA2324 pull request #313
Opened 2023-12-10 20:02 UTC by tonifaura

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [x] He probado mi código y funciona en local
- [x] He validado que mi código es correcto a niveles de formato
- [x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [x] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-12-11 10:34 UTC, martinImagina requested changes
- import requests (bien)
+ import requestS (mal)

OJO porque la librería acaba con s y no con S

2023-12-13 14:42 UTC, tonifaura commented
Buenas,
Ya he pusheado la corrección del ejercicio mas el ejercicio final, pero esta vez despues de hacer Push, ya no me sale la opción de hacer la Pull Request en github desktop, por que puede ser?

2023-12-13 17:14 UTC, martinImagina commented
Misma situación que en el oto repositorio. ¿Se necesita que haga alguna cosa por aquí? ¿@tonifaura,  @a10pepo? Me ponía que se había solicitado mi review pero actualmente no me indica que tenga que revisar ningún archivo en particular.

2023-12-14 17:39 UTC, a10pepo commented
> Misma situación que en el oto repositorio. ¿Se necesita que haga alguna cosa por aquí? ¿@tonifaura, @a10pepo? Me ponía que se había solicitado mi review pero actualmente no me indica que tenga que revisar ningún archivo en particular.

Te he reenviado la revisión, deberían salirte @martinImagina

2023-12-18 13:34 UTC, martinImagina approved these changes
Buen trabajo. Lo único que para facilitar la corrección, el mantenimiento, redurcir el nº de líneas, mejorar la extensibilidad (nuevas funciones que puedieras desarrollar) etc. deberías haber separado en distintos archivos/módulos los distintos ejercicios y planterlos como funciones reutilizables.

2024-01-02 09:31 UTC, merged