Ejercicios Python
a10pepo/EDEM_MDA2324 pull request #350
Opened 2023-12-18 15:12 UTC by pabloivorra

# PULL REQUEST

Disculpar a demora he tenido cierto problemas con mi Github.

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [X] He probado mi código y funciona en local
- [X ] He validado que mi código es correcto a niveles de formato
- [X] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [X] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

"Mejor llego en cámara lenta, que quedarme en el trailer."

2023-12-18 15:19 UTC, martinImagina commented on Alumnos/FS/Pablo_Ivorra/DOCKER/dockerfile
Este archivo no me compete a mi revisarlo :) Aunque veo que has usado Docker para escoger una imagen con Python 3.11.4 instalada previamente y poder copiarte un archivo Python para finalmente ejecutarlo. Muy interesante ;D

2023-12-18 15:23 UTC, martinImagina commented on Alumnos/FS/Pablo_Ivorra/Python/Ejercicios/Sesion 1/ejercicio_sesion1
Podrías haber usado f"Hola {nombre}"

2023-12-18 15:25 UTC, martinImagina commented on Alumnos/FS/Pablo_Ivorra/Python/Ejercicios/Sesion 2/ejercicios_sesion2.py
Ojo porque podrías echarle un vistazo a [este enlace](https://programming-21.mooc.fi/part-6/3-errors) y evitar que el usuario final de tu código introduzca un valor que luego no pueda pasarse a float o int (cotrol de tipos).

Esto podrías aplicarlo al resto de proyectos ;)

2023-12-18 15:27 UTC, martinImagina requested changes
Te he dejado comentarios y hay archivos que parecen estar mal alojados. Revísalo @pabloivorra con @a10pepo

2023-12-18 15:27 UTC, martinImagina commented on Profesores/Kafka/src/main/python/exercise3/client.properties
Creo que este archivo no va a aquí.

2023-12-18 15:27 UTC, martinImagina commented on Profesores/Kafka/src/main/python/exercise3/consumer.py
Creo que este archivo no va aquí.

2023-12-18 15:27 UTC, martinImagina commented on Profesores/Kafka/src/main/python/exercise3/producer.py
Creo que este archivo tampoco va aquí ;)

2023-12-18 15:34 UTC, pabloivorra commented on Profesores/Kafka/src/main/python/exercise3/producer.py
Perdona Martin, fallo mio

2023-12-19 11:22 UTC, a10pepo requested changes
Ficheros vacíos y debes separar entregables por ramas

2023-12-21 18:23 UTC, closed without merging