Linuxbranchpabloivorra
a10pepo/EDEM_MDA2324 pull request #351
Opened 2023-12-18 16:07 UTC by pabloivorra

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [x] He probado mi código y funciona en local
- [x] He validado que mi código es correcto a niveles de formato
- [x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [x] No he copiado mi código porque soy una persona muy responsable :-)

2023-12-18 16:10 UTC, martinImagina commented on Alumnos/FS/Pablo_Ivorra/Linux/README.MD
Este archivo creo que no va aquí

2023-12-18 16:10 UTC, martinImagina commented on Alumnos/FS/Pablo_Ivorra/Linux/ej14_10_23.sh
Este archivo no es del curso de Python. Sino del de Linux

2023-12-18 16:11 UTC, martinImagina commented on Profesores/Kafka/src/main/python/exercise3/client.properties
Este archivo no es del curso de Python

2023-12-18 16:11 UTC, martinImagina commented on Profesores/Kafka/src/main/python/exercise3/producer.py
Este archivo no es del curso de Python

2023-12-18 16:11 UTC, martinImagina commented on Profesores/Kafka/src/main/python/exercise3/consumer.py
Este archivo no es del curso de Python

2023-12-19 11:21 UTC, a10pepo requested changes
No está lo que toca

2023-12-19 11:21 UTC, a10pepo commented on Alumnos/FS/Pablo_Ivorra/Linux/README.MD
Ficheros Vacíos

2023-12-19 11:21 UTC, a10pepo commented on Alumnos/FS/Pablo_Ivorra/Linux/ej14_10_23.sh
Fichero Vacío

2023-12-26 20:00 UTC, closed without merging