SQL Luis Segura
a10pepo/EDEM_MDA2324 pull request #357
Opened 2023-12-20 09:33 UTC by Luseca

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [X] He probado mi código y funciona en local
- [X] He validado que mi código es correcto a niveles de formato
- [X] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [X] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

![CapturaDocker1](https://github.com/a10pepo/EDEM_MDA2324/assets/148787198/f58e2cc6-58c4-4541-9491-6359bad595f4)
![CapturaDocker2](https://github.com/a10pepo/EDEM_MDA2324/assets/148787198/7257ac63-2315-460c-b399-b14668953e04)
![SQL 2](https://github.com/a10pepo/EDEM_MDA2324/assets/148787198/ea974c51-f3ea-45df-9839-269e9f785933)
![SQL 3](https://github.com/a10pepo/EDEM_MDA2324/assets/148787198/884456bf-dedd-4df8-8d30-7bd5b3a38a7b)
![SQL1](https://github.com/a10pepo/EDEM_MDA2324/assets/148787198/d66b2a7d-041e-4894-a904-28da8cc57870)

2023-12-22 08:46 UTC, a10pepo commented
Esto no se puede mergear... estas borrando los archivos del ejercicio original

2023-12-22 08:47 UTC, a10pepo requested changes

2023-12-22 08:47 UTC, a10pepo commented on Alumnos/ES/Luis_Segura/SQL/docker_database_with_pgadmin.md
Por qué renombras? tienes que copiar a tu carpeta

2024-01-15 15:14 UTC, gavnatalia approved these changes

2024-01-16 11:04 UTC, closed without merging