Kafka_PostWork
a10pepo/EDEM_MDA2324 pull request #369
Opened 2023-12-25 18:52 UTC by cmarty02

Entrega del postwork de Kafka

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/110429018/964b2d2d-8119-46e3-8316-db53228cde70)

2023-12-25 18:55 UTC, cmarty02 commented
@rusansor Profe, va el post work de Kafka. Saludos!

2023-12-27 08:22 UTC, rusansor requested changes
Hola Cristian.

Me ha encantado el caso de uso, y el resultado final que obtienes. Y que hayas combinado finalmente el Producer, Consumer con Ksql.

Y está muy bien documentado.

Como mejoras, de un trabajo ya muy bueno!, te propongo refactorices el código Python, creando métodos encapsulados para cada operación.  De lo contrario en una App real, el código que ahora es fácil de seguir, sería complicado de seguir y de mantener.

2023-12-27 14:39 UTC, cmarty02 commented
@rusansor Gracias profe! yo también disfrute mucho desarrollándolo. 
Gracias también por la sugerencia, ya que aún me cuesta trabajar con clases y es algo que me hicieron notar otros docentes. 
Subo el commit con el código refactorizado.  
Saludos.-

2024-02-15 09:27 UTC, rusansor approved these changes

2024-02-15 09:43 UTC, cmarty02 commented
@pedronieto1206 @rusansor Debo crear otra pull request con los cambios? No entiendo por que se cerro esta. No me queda claro como proceder en este caso. Agradezco aclaración.

2024-02-15 14:24 UTC, pedronieto1206 commented
Estaba bien, creo que Ruben la ha cerrado por error.

2024-02-15 20:07 UTC, cmarty02 commented
@pedronieto1206 creo que no se mergeo

2024-02-16 08:10 UTC, merged