Kafka project
a10pepo/EDEM_MDA2324 pull request #377
Opened 2023-12-29 12:14 UTC by juancl90

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/145840791/086b146a-628c-4265-8bb9-07c39755642c)

El de arriba soy yo configurando el dockerfille, docker-compose y su conexión con kafka jajajaja

Asumo y entiendo que es una subida grande, para facilitaros la vida he añadido un Read.me con bastante explicación y detalle.

Aprovecho para desearte una feliz navidad Pedro!! Un abrazo enorme ^^

2024-01-08 08:51 UTC, rusansor commented on Alumnos/FS/JUAN CORNEJO/KAFKA/KP_5_Consumidor_y_productor.py
> +    # Configuración del consumidor
Para mejorar tus skills de CLEAN CODE, necesito que refactorices el código para que NO tenga comentarios. De tal forma que el código fuese tan autodescriptivo que los comentarios fuesen mínimos y solo haya donde hayan de dar un contexto de algo complicado.

Puedes sonar a aberración, pues siempre se ha dicho que hay que poner comentarios en el código, pero la nueva escuela sería esta. En vez de poner el comentario "# Configuración del consumidor" puedes crear un método Python que se llame "getConsumerConfiguration()"

2024-01-08 08:56 UTC, rusansor commented
No encuentro el ficher de EVIDENCIA del código en ejecución, con capturas de pantalla de los resultados.

A parte de eso te he puesto comentarios de petición de más modularización del código en métodos Python.

A parte de estos dos detalles, veo que te has currado el proyecto, la business idea, y la implementación. Muy bien ;)!!

2024-01-08 13:55 UTC, rusansor requested changes

2024-01-09 09:38 UTC, juancl90 commented on Alumnos/FS/JUAN CORNEJO/KAFKA/KP_5_Consumidor_y_productor.py
> +    # Configuración del consumidor
Hola Rubén! Muchas gracias por el feedback. Me pongo de inmediato con ello :-)

2024-01-09 09:42 UTC, juancl90 commented
> No encuentro el ficher de EVIDENCIA del código en ejecución, con capturas de pantalla de los resultados.
> 
> A parte de eso te he puesto comentarios de petición de más modularización del código en métodos Python.
> 
> A parte de estos dos detalles, veo que te has currado el proyecto, la business idea, y la implementación. Muy bien ;)!!

Muchas gracias, sí la verdad es que le puse cariño jajaja

El fichero de resultados serían los json adjuntos. En uno están recogidos los datos del primer productor que llegan al topic 1, y en otro los datos del topic final, que incluyen la dirección añadida mediante un script de python. El hecho de que ya lleven dirección y que sean registros que se encuentran en el del primer productor indicarían a priori que el proceso se ha ejecutado de forma transversal satisfactoriamente. Lo que sí me faltarían son las capturas de pantalla, que si te parece las subo cuando actualice el código según los comentarios.

Un abrazo enorme!

2024-01-09 09:53 UTC, juancl90 commented on Alumnos/FS/JUAN CORNEJO/KAFKA/KP_5_Consumidor_y_productor.py
> +    # Suscribirse a un tópico
Aprovecho también para preguntarte Rubén, ¿me recomendarías que empiece a escribir desde ya todo el código que pueda en inglés? ¿Suele ser lo más habitual?

2024-01-09 10:23 UTC, rusansor commented on Alumnos/FS/JUAN CORNEJO/KAFKA/KP_5_Consumidor_y_productor.py
> +    # Suscribirse a un tópico
Hola Juan,

pues sí, es lo habitual. Al menos en mi entorno de empresas multinacionales!!! No sé que harán en España en empresas locales.

**Yo te recomiendo en inglés ;)!!!!** es nuestra "lengua franca" en el mundo del Software(Tutoriales, Videos Tech en Youtuve, Conferencias, Meetings con clientes y compañeros de trabajo, documentación, etc etc.), hay cosas que nos cuestan decirlas en castellano por el día a día :D!!!!

2024-01-12 09:32 UTC, juancl90 commented
Hola @rusansor ,

He realizado algunos ajustes al código para que sea algo más limpio.  En KP_1 he creado una clase para el Productor y otra para el Consumidor-Productor. Aunque no hay tantos cambios como me gustaría, creo que de esta forma los scripts quedan algo más limpios y entendibles. 

Cualquier otro cambio o seguir mejorando el código, dime sin problemas

Un abrazo enorme Rubén.

2024-02-15 09:30 UTC, rusansor commented
Genial Juan!! aprobado. Buen trabajo, gracias!!

2024-02-15 16:16 UTC, merged