Kafka+Flask
a10pepo/EDEM_MDA2324 pull request #384
Opened 2024-01-02 15:28 UTC by juancl90

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/145840791/ff737fce-ac2c-47ea-9a8b-cf6621499674)

Feliz año Pedro!

Una vez terminado el ejercicio de Flask y de Kafka, he pensado que ya que estábamos, sería divertido juntarlos ambos.

Básicamente el ejercicio es similar al entregado de Kafka, pero esta vez extraigo los datos de una api levantada en Flask, y he vuelto a dockerizar todo el proceso para que funcione salvo la descarga e impresión (que va por fuera), y una función para ejecutar procesos en paralelo (y que simule mejor tiempo real).

He actualizado también el README.md con los cambios más significativos de este nuevo ejercicio.

Por comodidad para ti, te los pego aquí también:

# DIFERENCIAS VS PROYECTO KAKFA (Entregable anterior)
* Para complicar el caso, he probado a juntar el entregable de Kafka con el de Flask.
* Para ello, el Productor inicial obtendrá la información de una api levantada con Flask y que ofrecerá datos aleatorios (y coherentes: por ejemplo, vienen en orden cronológico todos los datos). El productor los recogerá y los enviará al Topic de entrada en Kafka.
* Para simular mejor el tiempo real, he probado a usar la función de python threading para ejecutar el productor 1 y el transformador (consumidor+modficiación+productor) en paralelo. De esta forma, se simula mejor el tiempo real y no hay que esperar hasta que se ejecute el código del primer productor para ir viendo como fluyen los datos a través de los topics.
* Al igual que el ejercicio previo, está todo dockerizado. En este caso, he necesitado construir dos imágenes en docker, una para el script de python de Kafka, y otra para levantar la api.

2024-01-09 08:37 UTC, a10pepo requested changes
Por qué esta jutno flask y kafka en la misma carpeta??? separalo please

2024-01-09 09:30 UTC, juancl90 commented
> Por qué esta jutno flask y kafka en la misma carpeta??? separalo please

Hola Pedro! Está junto porque es un ejercicio especial que decidí hacer (basicamente es el ejercicio de Kafka que pero recogiendo los primeros datos de una api creada por mi en flask). No obstante, en otras ramas (y pulls ya hechas) tengo dos carpetas separadas una para flask y otra para kafka. Por aclararlo, tengo 3 carpetas (una para flask, otra para kafka y otra para este trabajo especial que hice kafka+flask).

Siendo así, entiendo no sería necesario no?

2024-02-14 08:15 UTC, NuriaUrena reviewed
Da error porque en el path le falta /
![image](https://github.com/a10pepo/EDEM_MDA2324/assets/50206702/8d4f32bd-00f3-4b40-8979-158b5a9272d4)

Auqnue no es el que se ha pedido como ejercicio extra me sirve para ver que se ha entendido:)

2024-02-15 09:41 UTC, rusansor approved these changes

2024-02-15 09:41 UTC, rusansor commented on Alumnos/FS/JUAN CORNEJO/KAFKA+FLASK/KP_1_Definicion_clase.py
> +    tipo_emergencia = {
Está muy guau el caso de uso, y mezclar kafka con Flask!

2024-02-15 16:14 UTC, a10pepo approved these changes

2024-02-15 16:15 UTC, merged