Kafka Postwork
a10pepo/EDEM_MDA2324 pull request #385
Opened 2024-01-02 19:59 UTC by jorgedom5

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

Soy literalmente este tío cuando ha tocado hacer la parte de docker
![image](https://github.com/a10pepo/EDEM_MDA2324/assets/148787367/be1876b0-b831-4037-a57f-ce41117b89bd)

2024-01-08 11:11 UTC, jorgedom5 commented
@rusansor no se te ha puesto de reviewer

2024-01-08 13:53 UTC, rusansor requested changes

2024-01-08 13:53 UTC, rusansor commented on Alumnos/ES/Jorge_Dominguez/kafka/readme.md
La images está rota, la puedes fixear?
![image](https://github.com/a10pepo/EDEM_MDA2324/assets/236189/978c979d-983d-450e-b915-a3bcba910ddc)

2024-01-08 20:16 UTC, jorgedom5 commented on Alumnos/ES/Jorge_Dominguez/kafka/readme.md
@rusansor la he puesto en el comentario de la pull request

2024-01-09 07:38 UTC, rusansor commented on Alumnos/ES/Jorge_Dominguez/kafka/readme.md
Eso no nos sirve, en un proyecto real no se puede quedar la documentación rota, te muestro como puedes replicarlo y ver que on funciona en GitHub

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/236189/2abd00e2-1045-4d0e-9b23-2a170f790b56)

Con una búsqueda rápida en internet veo esto https://stackoverflow.com/questions/10189356/how-to-add-screenshot-to-readmes-in-github-repository de donde veo como opción que uses la ruta absoluta. 

Por favor intenta arreglarlo y testarlo tú mismo. 

Gracias!!

2024-01-09 07:50 UTC, jorgedom5 commented
@rusansor vale creo que ya, me faltaba el punto de la ruta

2024-01-09 08:02 UTC, rusansor requested changes

2024-01-09 08:02 UTC, rusansor commented on Alumnos/ES/Jorge_Dominguez/kafka/readme.md
"De esta forma es más fácil poder sacar conclusiones mediante el uso de queries en KSQL."

no veo el código Ksql. ni el pipeline complejo que se pedia de encadenar algún producer => consumer => producer > consumer o combinado con ksql.

Puedes hacer algún flujo algo más complejo basado con tu caso de uso?

Gracias!!

2024-01-09 08:06 UTC, jorgedom5 commented on Alumnos/ES/Jorge_Dominguez/kafka/client.properties
si, pero lo he hecho de las 2 formas ya que para probar los mensajes lo usé en local, y cuando funcionaba ya me encargué de montar el docker

2024-01-09 11:01 UTC, jorgedom5 commented on Alumnos/ES/Jorge_Dominguez/kafka/readme.md
perfecto, anoto que tengo que hacerlo más complejo

2024-01-09 22:02 UTC, jorgedom5 commented
@rusansor ya he agregado funcionalidades a través de ksql, principalmente los cambios se encuentran en el readme con las capturas del proceso ksql

2024-02-15 09:31 UTC, rusansor commented
Genial gracias Jorge! aprovado, saludos!!

2024-02-15 09:51 UTC, jorgedom5 commented
Hola @rusansor, has cerrado la PR

2024-02-15 16:14 UTC, merged