Kafka
a10pepo/EDEM_MDA2324 pull request #396
Opened 2024-01-05 14:10 UTC by pepe54aguilar

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [x] He probado mi código y funciona en local
- [x] He validado que mi código es correcto a niveles de formato
- [x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [x] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P
![bocman_XX_Bocenharbie](https://github.com/a10pepo/EDEM_MDA2324/assets/42940865/a3a0ae9e-7017-4176-8f86-36460d41746e)

2024-01-08 13:49 UTC, rusansor requested changes

2024-01-08 13:49 UTC, rusansor commented on Alumnos/FS/Pepe_Aguilar_van_der_Hofstadt/KAFKA/README.md
Hola Pepe, 

antes de seguir con el Code Review necesito arregles las urls de las imágenes en el README.md, están ahora rotas

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/236189/fa93a29b-6aca-44d4-a1ff-2dc5f6942d8f)


Además te voy a dejar comentarios de ficheros/carpetas que no deberías subir a al repo git.

2024-01-08 13:49 UTC, rusansor commented on Alumnos/FS/Pepe_Aguilar_van_der_Hofstadt/KAFKA/.idea/vcs.xml
esta carpeta no la deberías de subir. Son fichero de config del editor Intellij IDE que es buan práctica no subir, pq en un equipo cada uno lo tiene montado a su gusto. Si lo subes rompes al resto de compis.

Pero es que además veo/creo que está fuera de *tu* carpeta personal, con lo cual menos aún subirla.

2024-01-08 13:49 UTC, rusansor commented on Alumnos/FS/Pepe_Aguilar_van_der_Hofstadt/KAFKA/.idea/vcs.xml
Primero antes que nada CHAPO y mi enhorabuena que te hayas atrevido ha hacerlo en Java ;) :)!!!!!!

esta carpeta NO la tienes que subir a git. FYI si usan Java/Maven el código compiado de Java va por defecto a esta carpeta target. Esto es código compilado que NO tienes que subir a git.

2024-01-09 01:06 UTC, pepe54aguilar commented on Alumnos/FS/Pepe_Aguilar_van_der_Hofstadt/KAFKA/README.md
Buenas noches Ruben.

He estado probando e investigando un poco sobre que ha podido pasar en las imagenes (me funciona en local) y creo a que se debe a un "error" en el apartado de 'files chaged'. 
Mi teoria de lo que ocurre, es que el README.md intenta acceder a la ruta de la imagen en la rama main del repositorio de pedro, y al no estar aceptada la pull request, aun no hay nada y por eso no aparece ninguna imagen.
De todas formas me he hecho un auto pull request a mi repositorio personal, en el siguiente enlace podrás ver el README.md de forma correcta. [repositorio de jose/pepe](https://github.com/pepe54aguilar/EDEM_MDA2324/tree/main/Alumnos/FS/Pepe_Aguilar_van_der_Hofstadt/KAFKA)
En cuanto a los demás cambios, ya he borrado las carpetas que no se deben subir a git.

2024-01-22 15:20 UTC, merged