ejercicio kafka entregable
a10pepo/EDEM_MDA2324 pull request #398
Opened 2024-01-06 11:18 UTC by albertodegeapla

Ejercicio entregable kafka Ruben Sanchís

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-01-09 08:07 UTC, rusansor requested changes

2024-01-09 08:07 UTC, rusansor commented on Alumnos/FS/ALBERTO_DE_GEA/KAFKA/readme.md
Hola Alberto!

¿Puedes elaborar la documentación de este readme.md con los requerimientos que comentarmos en https://github.com/a10pepo/EDEM_MDA2324/tree/main/Profesores/Kafka/PostWork?

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/236189/f95f008f-a443-4af9-8485-71f36c740970)

2024-01-09 08:13 UTC, albertodegeapla commented
Hola Rubén,

Claro. Esta tarde te lo subo completo.

Un saludo. Alberto De Gea Pla


El El mar, 9 ene 2024 a las 9:07, rusansor ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On Alumnos/FS/ALBERTO_DE_GEA/KAFKA/readme.md
> <https://github.com/a10pepo/EDEM_MDA2324/pull/398#discussion_r1445747958>:
>
> Hola Alberto!
>
> ¿Puedes elaborar la documentación de este readme.md con los requerimientos
> que comentarmos en
> https://github.com/a10pepo/EDEM_MDA2324/tree/main/Profesores/Kafka/PostWork
> ?
>
> image.png (view on web)
> <https://github.com/a10pepo/EDEM_MDA2324/assets/236189/f95f008f-a443-4af9-8485-71f36c740970>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/a10pepo/EDEM_MDA2324/pull/398#pullrequestreview-1810595619>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BC2ZZSA5LY2K63RPHQ36GV3YNT3FNAVCNFSM6AAAAABBPPQ6PSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMJQGU4TKNRRHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-10 21:23 UTC, albertodegeapla commented on Alumnos/FS/ALBERTO_DE_GEA/KAFKA/readme.md
Hola, lo he dejado a medias. Mañana lo termino, por si vas a revisarlo que lo tengas en cuenta que todavía me falta una parte por entregar.

2024-02-15 09:34 UTC, rusansor approved these changes
Aprobado, gracias!

2024-02-15 09:34 UTC, rusansor commented on Alumnos/FS/ALBERTO_DE_GEA/KAFKA/readme.md
ok gracias!!

2024-02-15 16:16 UTC, merged