Docker
a10pepo/EDEM_MDA2324 pull request #410
Opened 2024-01-12 14:44 UTC by pamano21

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-01-13 13:52 UTC, a10pepo requested changes
No sé xq has borrado archivos de otros compañeros...

2024-01-13 15:31 UTC, pamano21 commented
Buenas Pedro.

Perdón si he hecho algo que no tocaba, te acuerdas que te comente que lo
había subido? ayer llegue a clase y pregunte con varios compañeros y en no
se porque en mi git hub me salían archivos de muchos compañeros. Siento
haber liado.

Cualquier cosa me dices.

un saludo

El sáb, 13 ene 2024 a las 14:52, Pedro Nieto ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> No sé xq has borrado archivos de otros compañeros...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/a10pepo/EDEM_MDA2324/pull/410#pullrequestreview-1820020596>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCYVU6RWSQ5NILJKWK27ESLYOKGQZAVCNFSM6AAAAABBYHZQ4SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMRQGAZDANJZGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-16 11:30 UTC, a10pepo approved these changes

2024-01-16 11:31 UTC, a10pepo commented
Te he arreglado yo la rama para que se pueda mergear.. pero esto era tarea tuya...

2024-01-16 11:31 UTC, merged