PYTHON - Sesiones 4 y 5 + Proyecto FInal
a10pepo/EDEM_MDA2324 pull request #452
Opened 2024-01-21 01:57 UTC by FernandoCabreraCarbonell

He terminado los ejercicios de las sesiones 4 y 5 y he completado el proyecto final. (con png confirmando que funciona)

Tambien he corregido el nombre de los archivos de la sesion 3 que no tenían el .py

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-01-23 14:17 UTC, martinImagina requested changes
Buenas. en mi solicitud de aprobación, **se me indica que hay 2025 archivos que revisar**. 

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/5cf732ca-d5e7-4493-b3cb-41a1ed8b37a2)

Entiendo (y espero jajaja) que se trata de un error. Antes de ponerme a revisar todos los ficheros, por favor @FernandoCabreraCarbonell revisa tu configuración de ramas y solicitud de revisión.

En caso de que tengas dudas, debes preguntarle a @a10pepo para que te pueda echar un cable.

2024-01-23 16:30 UTC, FernandoCabreraCarbonell commented
> Buenas. en mi solicitud de aprobación, **se me indica que hay 2025 archivos que revisar**.
> 
> ![image](https://private-user-images.githubusercontent.com/41681622/298969629-5cf732ca-d5e7-4493-b3cb-41a1ed8b37a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjYzNTUsIm5iZiI6MTcwNjAyNjA1NSwicGF0aCI6Ii80MTY4MTYyMi8yOTg5Njk2MjktNWNmNzMyY2EtZDVlNy00NDkzLWIzY2ItNDFhMWVkOGIzN2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE2MDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNWU4YzgxZTQwZjk4MWRmNDhlOTgzNTIwNGRlODNjOGJlZTRhNGRmOTJiZmVkMGIwODE4MmEwMjMzMWRjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.udv85fMpfB9sd4AjddlNGdqXl7f9K084pGZhDb3qZcg)
> 
> Entiendo (y espero jajaja) que se trata de un error. Antes de ponerme a revisar todos los ficheros, por favor @FernandoCabreraCarbonell revisa tu configuración de ramas y solicitud de revisión.
> 
> En caso de que tengas dudas, debes preguntarle a @a10pepo para que te pueda echar un cable.

He identificado el error.
Como en uno de los ejercicios se pedía crear un entorno virtual con el venv y requirements.txt y que se pueda ejecutar desde Visual...
- Al enviar los ejercicios, he adjuntado la carpeta entera en lugar de solamente la captura donde se veia la ejecución.

Creo que lo mejor es cerrar esta pull request y hacer otra sin esa carpeta.
Si me lo confirmais, lo hago así.

2024-02-03 11:57 UTC, FernandoCabreraCarbonell commented
hola @martinImagina esto sigue abierto ¿verdad?

2024-02-05 07:50 UTC, martinImagina commented on Alumnos/FS/FERNANDO-CABRERA-CARBONELL/PYTHON/EJERCICIOS_EVALUABLES/Sesión 4/Ejercicio 2/sesion04_ejercicio02.py
Archivo vacío. Solo está el enunciado del ejercicio.

2024-02-05 07:53 UTC, martinImagina approved these changes
Buen trabajo @FernandoCabreraCarbonell. ¡Saludos!

2024-02-05 08:06 UTC, merged