kafka entregable
a10pepo/EDEM_MDA2324 pull request #461
Opened 2024-01-23 00:49 UTC by StasKorotchenko

frases

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-02-05 08:23 UTC, rusansor requested changes
Hola @StasKorotchenko !!

necesitaría que añadas en el README.md una descripción de que Caso de Uso has implementado, y explicando que flujo de datos/procesado has implementado.

Gracias!!

2024-02-05 22:28 UTC, StasKorotchenko commented
@rusansor Hola
Gracias por tu commentario, he hecho update de readme.md

2024-02-15 09:37 UTC, rusansor approved these changes

2024-02-15 09:37 UTC, rusansor commented on Alumnos/FS/Stas Korotchenko/KAFKA/README.md
> +## DESPLIEGUE DE LA APLICACIÓN:
ok gracias por la doc!!

2024-02-15 16:16 UTC, merged