Crear carpeta retos python
a10pepo/EDEM_MDA2324 pull request #49
Opened 2023-10-18 10:23 UTC by juancl90

Hola Pedro, he buscado en la lista desplegable para ver si veía el usuario de Martin en Github para que aprobase la Pull, pero salvo que quizás se me haya pasado, no lo he encontrado.

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-10-18 19:57 UTC, a10pepo commented
@martinImagina he puesto lintin process para el codigo de python, si crees que es demasiado para ellos lo quito...

2023-10-18 20:03 UTC, a10pepo requested changes
La carpeta pycache no se sube a git, borrala de tu rama

2023-10-19 15:02 UTC, juancl90 commented
He borrado la carpeta de esta branch y creo que he vuelto a re-activar la solicitud de pull.

2023-10-19 15:04 UTC, a10pepo approved these changes
Muy bien, espera el approve de Martin no mergees

2023-11-21 21:03 UTC, a10pepo commented
@martinImagina nos hace falta tu review

2023-11-22 12:48 UTC, martinImagina commented on Alumnos/FS/JUAN CORNEJO/RETOS PYTHON - MARTIN/R01y02_preparation.py
Buen trabajo empleando clases para definir los datos de un disco :)

2023-11-22 12:52 UTC, martinImagina approved these changes
Muy buen trabajo. Revisa los comentarios que te he puesto en el proyecto final de la cartera de clientes :D

2023-11-28 21:42 UTC, merged