Analisis salarios data
a10pepo/EDEM_MDA2324 pull request #50
Opened 2023-10-18 19:39 UTC by pepe54aguilar

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-10-18 19:58 UTC, a10pepo requested changes
Tu PR tiene más de 1000 archivos... limpia todo lo que no sea necesario!!!

2023-10-19 15:08 UTC, pepe54aguilar commented
Por algún motivo que no entiendo, cada vez que utilizo github para hacer mis cosas (el análisis que había que hacer) como que te hace automáticamente un pull request. 

¿Qué puede estar pasando?

2023-10-19 15:35 UTC, a10pepo commented
Tienes dos PR abiertas, una desde main otra desde tu rama de análisis. La pull request la creas tu la primera vez y luego se queda hecha hasta que se cierra.. siempre está ahí.

2023-10-19 15:48 UTC, pepe54aguilar commented
entonces para que no se autopulle cualquier cambio que haga tendría que cerrar la pull request desde mi main no?
la tengo que cerrar yo o eso deberias hacerlo tu cuando esté todo correcto?

2023-10-21 13:03 UTC, a10pepo commented
Cuando creas la PR haces unes tu rama a que yo la revise, todo cambio que hagas commit en ella yo lo veré. Eso estará abierto hasta q la PR se cierre, ya seas tú porque la canceles o yo porque la apruebe...

2023-10-27 13:58 UTC, closed without merging