udpate
a10pepo/EDEM_MDA2324 pull request #53
Opened 2023-10-20 14:11 UTC by albertodegeapla

crear carpetas para los ejercicios

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-10-21 13:11 UTC, a10pepo requested changes

2023-10-21 13:11 UTC, a10pepo commented on Alumnos/FS/ALBERTO_DE_GEA/ejercicio_2/script.sh
Falta la cabecera del script

2023-11-05 13:54 UTC, a10pepo requested changes

2023-11-05 13:54 UTC, a10pepo commented on Alumnos/FS/ALBERTO_DE_GEA/SCRIPT.SH/script.sh
Falta cabecera

2023-11-11 17:02 UTC, alhercan approved these changes
Buen Trabajo

2023-11-13 07:59 UTC, martinImagina approved these changes
Los entregables y retos de Python subidos son correctos. Aún así, faltan ejercicios de varias sesiones y el proyecto Final :) Aprouebo de momento esta subida. Cuando subas el resto, te los reviso :)

2023-11-13 08:17 UTC, a10pepo approved these changes

2023-11-13 08:17 UTC, merged