KAKFA
a10pepo/EDEM_MDA2324 pull request #546
Opened 2024-02-21 19:31 UTC by mapova

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-02-28 12:52 UTC, rusansor requested changes
Hola Mar,

necesito por favor que documentes el caso de uso que has diseñado, y pantallazon con las evidiencias de la ejecución del mismo. Gracias!!

2024-02-28 12:52 UTC, rusansor commented on Alumnos/FS/MAR-PONS-VALVERDE/KAKFA/POSTWORK/README
Hola Mar,

necesito por favor que expliques en este fichero el caso de uso que has diseñado, y pantallazon con las evidiencias de la ejecución del mismo. Gracias!!

2024-02-28 19:02 UTC, mapova commented on Alumnos/FS/MAR-PONS-VALVERDE/KAKFA/POSTWORK/README
buenas Rubén, 

te los acabo de subir a la misma rama. Ya me dices si lo has recibido y sino te lo vuelvo a subir. 

muchas gracias

2024-03-07 13:58 UTC, rusansor approved these changes

2024-03-11 08:22 UTC, merged