kafka ej pablo
a10pepo/EDEM_MDA2324 pull request #593
Opened 2024-02-28 20:03 UTC by pamano21

ee

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-03-04 07:41 UTC, rusansor requested changes
Hola Pablo,

el README está vacio. Necesito documentes cual es tu caso de uso y lo subas a github. Gracias!!

2024-03-06 12:57 UTC, pamano21 commented
Buenas Ruben.

Ya he hecho el commit con el nuevo readme.

De todas formas, te adjunto el readme por aqui por si Pedro está muy liado.

Hola Rubén, este es mi postwork. He utilizado los conocimientos de clase
para leer un libro al completo.
Esto es lo que he hecho:
1. He importado un libro en formato txt.
2. He creado un topic llamado "ALQUIMISTA"
3. Lo he producido a traves de mi producer.py
4. He leído todo lo que había producido en el producer en una terminal con
este código: docker-compose exec kafka kafka-console-consumer --topic
ALQUIMISTA --from-beginning --bootstrap-server localhost:9092
5. He abierto Ksql.
6. Por último, he realizado algunas queryS. Tienes capturas de pantalla.

El lun, 4 mar 2024 a las 8:42, rusansor ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Hola Pablo,
>
> el README está vacio. Necesito documentes cual es tu caso de uso y lo
> subas a github. Gracias!!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/a10pepo/EDEM_MDA2324/pull/593#pullrequestreview-1913553503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCYVU6VUWRPE6OC3UHDRTSDYWQQVBAVCNFSM6AAAAABD6VNYJGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMJTGU2TGNJQGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-06 12:58 UTC, a10pepo commented
Pedro no necesita hacer nada 😆 ruben lo puede ver en la PR

2024-03-06 13:00 UTC, pamano21 commented
Vaya! 🤣 yo era por nos molestar jajajjaa

Sorry ( que rapidez a)

Pd( ya que estamos) el ejercicio de Spark yo lo hice con Alberto De Gea

El El mié, 6 mar 2024 a las 13:58, Pedro Nieto ***@***.***>
escribió:

> Pedro no necesita hacer nada 😆 ruben lo puede ver en la PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/a10pepo/EDEM_MDA2324/pull/593#issuecomment-1980814288>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCYVU6TWRZMBSQZDEIC3LVDYW4HIDAVCNFSM6AAAAABD6VNYJGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBQHAYTIMRYHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-07 14:02 UTC, rusansor approved these changes
El caso de uso creo no es original en el sentido que creo es el que hicimos en clase.

Pero veo has usado otro libro como input y has ejecutado todo end to end por tu cuenta. OK.

Saludos!!

2024-03-11 08:18 UTC, merged