Kafka
a10pepo/EDEM_MDA2324 pull request #597
Opened 2024-02-29 12:41 UTC by Paugb01

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [x ] He probado mi código y funciona en local
- [x ] He validado que mi código es correcto a niveles de formato
- [x ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [x ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P
![docker](https://github.com/a10pepo/EDEM_MDA2324/assets/78257330/a38c0f7e-56a9-4b05-8ea0-68b4499bb610)

2024-03-04 07:45 UTC, rusansor requested changes
Hola,

necesito subas algún README.md, o fichero de texto donde documentes tu Caso de Uso. Gracias!!

2024-03-07 14:05 UTC, rusansor requested changes
Hola @Paugb01 !!

no te puedo aceptar esta PR porque parece le estás borrando contenido a otros compañeros. Te adjunto captura de pantalla para que lo veas. Lo puedes revisar please?

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/236189/f4bd67fb-938a-4a9e-b0a1-4f5d211db512)

2024-03-07 14:54 UTC, Paugb01 commented
> Hola,
> 
> necesito subas algún README.md, o fichero de texto donde documentes tu Caso de Uso. Gracias!!

Hecho Rubén! :)

2024-03-07 14:55 UTC, Paugb01 commented
> Hola @Paugb01 !!
> 
> no te puedo aceptar esta PR porque parece le estás borrando contenido a otros compañeros. Te adjunto captura de pantalla para que lo veas. Lo puedes revisar please?
> 
> ![image](https://private-user-images.githubusercontent.com/236189/310906147-f4bd67fb-938a-4a9e-b0a1-4f5d211db512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjM1MDgsIm5iZiI6MTcwOTgyMzIwOCwicGF0aCI6Ii8yMzYxODkvMzEwOTA2MTQ3LWY0YmQ2N2ZiLTkzOGEtNGE5ZS1iMGExLTRmNWQyMTFkYjUxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNDUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWQ1OTQ4Y2M5ZTM3ZjM0YTI1N2EyNzQzMTA3Y2ZiYWRjYjgxOGNjYWEzMmI3MTAyOWQ1ODdjMjAzNmM2N2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-Jord4CorKy7pIaSoE7zeDvpWLF33mTgreCMnMisVno)

Con respecto a esto, lo siento, no sé qué hice. He reseteado la rama, ya está solucionado.

2024-03-11 07:33 UTC, rusansor approved these changes
Aprovado, gracias Pau!

2024-03-11 07:33 UTC, rusansor commented on Alumnos/ES/Pau_Garcia/KAFKA/README.md
> +En nuestra demo hemos rastreado los vuelos que están a más de 25000 pies y van a más de 380 nudos.
OK!!

2024-03-11 07:33 UTC, rusansor commented on Alumnos/ES/Pau_Garcia/KAFKA/radar.json
good model ok!

2024-03-11 07:33 UTC, rusansor commented on Alumnos/ES/Pau_Garcia/KAFKA/ksql.sh
> +CREATE STREAM flight_radar (flight_number VARCHAR, airspeed INT, current_height INT) WITH (kafka_topic='points', value_format='JSON');
guay hayas documentado la KSQL!!

2024-03-11 07:33 UTC, rusansor commented on Alumnos/ES/Pau_Garcia/KAFKA/screenshots/query.png
evidencia ok, gracaias Pau!!

2024-03-11 08:18 UTC, merged