dataflow_entrega
a10pepo/EDEM_MDA2324 pull request #603
Opened 2024-02-29 13:23 UTC by cmarty02

Entregable dataflow. Sistema de control de velocidad

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/110429018/225850e1-c9f7-4f1d-b446-315dcc68507c)

2024-02-29 13:24 UTC, cmarty02 commented
Hola @jabrio , como estas? Va la entrega de dataflow. 
Saludos!

2024-02-29 16:05 UTC, jabrio requested changes
Hola @cmarty02 No has añadido la captura de los datos en BigQuery que básicamente era el entregable. He agradecido que hayas intentado extender un poco más el pipeline guardando las imágenes de los coches multados. Sube el código también ya que ha sido algo extra.

Te lo marco como cambios a modificar. En caso de que no tengas la captura y puesto que el deadline es hoy avísame y comentamos.

2024-02-29 19:02 UTC, cmarty02 commented
@jabrio entendido, commiteo la captura de bigquery con el readme actualizado.
Saudos!

2024-03-04 09:11 UTC, jabrio commented
Hola @cmarty02 Gracias por adjuntar la captura. Te apruebo la PR.

Un abrazo.

2024-03-04 09:11 UTC, jabrio approved these changes

2024-03-04 09:11 UTC, merged

2024-03-04 12:57 UTC, cmarty02 commented
Gracias @jabrio 
Abrazo!