Kafka
a10pepo/EDEM_MDA2324 pull request #610
Opened 2024-02-29 20:18 UTC by borjach26

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [x] He probado mi código y funciona en local
- [x] He validado que mi código es correcto a niveles de formato
- [x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [x] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-03-04 07:53 UTC, rusansor requested changes
Hola Borja,

necesito subas documento donde expliques tu Caso de Uso, que es lo que has implementado.

Gracias!!

2024-03-07 07:01 UTC, borjach26 commented
Hola Rubén,

ya he subido el readme con el caso de uso, que se me olvidó :(

@rusansor

2024-03-07 14:07 UTC, rusansor approved these changes

2024-03-07 14:07 UTC, rusansor commented on Alumnos/ES/BORJA_CABO/KAFKA/README.md
> +Para este entregable he usado un json con los mejores peleadores de la UFC a lo largo de la historía, en el que encontramos su nombre, sus victorías, sus derrotas, las finalizaciones que han consegui
OK El caso de uso me mola mucho UFC :D ;)!!!!!!! pero no sé si coincidremos en quién es el mejor peleador con las aficiones :)!!!

2024-03-07 14:07 UTC, rusansor commented on Alumnos/ES/BORJA_CABO/KAFKA/README.md
> +      "wins": "X",
ok!!

2024-03-07 14:07 UTC, rusansor commented on Alumnos/ES/BORJA_CABO/KAFKA/images/Producer.png
ok good evidence!

2024-03-07 14:07 UTC, rusansor commented on Alumnos/ES/BORJA_CABO/KAFKA/images/Consulta3.png
ok good evidence!

2024-03-11 08:17 UTC, merged