Ejercicio kafka
a10pepo/EDEM_MDA2324 pull request #617
Opened 2024-02-29 21:21 UTC by Luesdo

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2024-03-04 08:03 UTC, rusansor requested changes
Hola Lucía,

necesito subas a github un fichero donde expliques tu Caso de Uso.  Gracias!

2024-03-07 14:09 UTC, rusansor requested changes
Hola Lucía!

please puedes subir a esta PR el ficher README.md explicando tu caso de uso , y las evidencias/resultados de la ejecución con capturas de pantalla?

Gracias!!

2024-03-15 14:53 UTC, Luesdo commented
Hola! 

perdona por tardar en resolverlo, ya lo tienes! 

Muchas Gracias :)

2024-03-21 11:03 UTC, rusansor approved these changes

2024-03-21 11:03 UTC, rusansor commented on Alumnos/FS/Lucía-Esteve-Domínguez/Kafka/Clase_venta.py
> +    tipo_prenda = [
modelo propio, good!!

2024-03-21 11:03 UTC, rusansor commented on Alumnos/FS/Lucía-Esteve-Domínguez/Kafka/Clase_venta.py
> +        self.tipo_prenda = random.choice(list(venta.tipo_prenda))
veo has generado datos random, ok!!

2024-03-21 11:03 UTC, rusansor commented on Alumnos/FS/Lucía-Esteve-Domínguez/Kafka/Creacion_topics.py
> +    futures = admin_client.create_topics(new_topics)
muy bueno hayas usado el cliente admin para crear topics!!

2024-03-21 11:03 UTC, rusansor commented on Alumnos/FS/Lucía-Esteve-Domínguez/Kafka/consumer y creacion topics.jpeg
evidencia ok

2024-03-21 11:03 UTC, rusansor commented on Alumnos/FS/Lucía-Esteve-Domínguez/Kafka/readme.md
hubiese preferido un readme que explicara el caso de negocio, el modelo de negocio usado, etc.
Pero veo has trabajado el entregable a nivel de código, y lo damos por bueno.

Saludos!!

2024-03-25 14:45 UTC, merged