Readme + python
a10pepo/EDEM_MDA2324 pull request #87
Opened 2023-10-26 19:01 UTC by andrescervera

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [X ] He probado mi código y funciona en local
- [ X] He validado que mi código es correcto a niveles de formato
- [ X] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ X] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-10-26 19:03 UTC, andrescervera commented
Es carga pesada porque se ha acumulado Python, pero es una rama solo con Python y el readme general actualizado. A partir de aquí iré entregando con ramas más pequeñas

2023-10-26 20:05 UTC, a10pepo requested changes
Tienes que borrar toda la carpeta .venv

2023-10-26 22:46 UTC, andrescervera reviewed
carpeta .venv borrada

2023-10-26 22:52 UTC, andrescervera commented
no se si tengo que volver a hacer PR o te sale el cambio actualizado directamente

2023-11-06 10:59 UTC, martinImagina approved these changes
Gracias Andrés:

He visto que has subido todos o muchos de los los ejercicios de las sesiones y lo cierto es que los veo muy bien. 

Entiendo que aún te faltará el proyecto final de Python. Si necesitas alguna orientación indícamelo :) ¡Ánimo!

2023-11-06 12:30 UTC, a10pepo approved these changes

2023-11-06 12:30 UTC, merged