update
a10pepo/EDEM_MDA2324 pull request #92
Opened 2023-10-27 07:43 UTC by albertodegeapla

crear carpeta python
añadir ejercicio entregables
añadir ejercicios retos volunatrios

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-11-21 21:04 UTC, a10pepo commented
@martinImagina  nos hace falta review

2023-11-22 12:57 UTC, martinImagina commented on Alumnos/FS/ALBERTO_DE_GEA/Python/sesion 1/ejercicio 1.py
perfecto :) Este era fácil jeje

2023-11-22 12:57 UTC, martinImagina commented on Alumnos/FS/ALBERTO_DE_GEA/Python/sesion 1/ejercicio2.py
Perfecto.

2023-11-22 13:04 UTC, martinImagina commented on Alumnos/FS/ALBERTO_DE_GEA/Python/sesion 3/ejercicio1.py
A partir del comentario del ejercicio de la sesión 2, puedes mejorar esta respuesta si lo deseas y aplicar un control de que el usuario introduzca un dato válido.

2023-11-22 13:04 UTC, martinImagina commented on Alumnos/FS/ALBERTO_DE_GEA/Python/sesion 3/ejercicio2.py
Genial

2023-11-22 13:05 UTC, martinImagina commented on Alumnos/FS/ALBERTO_DE_GEA/Python/sesion 3/ejercicio3.py
Genial. Aún así las condiciones del año bisiesto podrías simplificarla en una sola. Inténtalo si quieres ;)

2023-11-22 13:06 UTC, martinImagina commented on Alumnos/FS/ALBERTO_DE_GEA/Python/sesion 5/ejercicio1
Pendiente.

2023-11-22 13:07 UTC, martinImagina commented on Alumnos/FS/ALBERTO_DE_GEA/Python/sesion 5/ejercicio2.py
Pendiente.

2023-11-22 13:07 UTC, martinImagina commented on Alumnos/FS/ALBERTO_DE_GEA/Python/sesion 5/ejercicio3.py
Pendiente.

2023-11-22 13:07 UTC, martinImagina commented on Alumnos/FS/ALBERTO_DE_GEA/Python/PROYECTO FINAL/proyecto-final.py
Pendiente. No cumple con lo solicitado

2023-11-22 13:08 UTC, martinImagina requested changes
Buenas. Algunos de los ejercicios están muy bien, **otros están pendientes (pues los archivos están vacíos o incompletos) y el proyecto final no está completo.**

Si subes una nueva versión de ello, indícamelo para que pueda valorarlos.

2023-11-24 13:50 UTC, albertodegeapla commented on Alumnos/FS/ALBERTO_DE_GEA/Python/sesion 2/ejercicio.py
lo reviso Martin, gracias

2023-11-27 07:35 UTC, martinImagina approved these changes
Genial. ¡Buen trabajo!

2023-11-28 21:41 UTC, a10pepo approved these changes

2023-11-28 21:41 UTC, merged