Proyecto final python
a10pepo/EDEM_MDA2324 pull request #95
Opened 2023-10-27 13:08 UTC by StasKorotchenko

# PULL REQUEST

Si has llegado hasta aquí es que ya estás preparado para hacer tu PR:

Antes de continuar... asegúrate de lo siguiente:

Pon una `x` en las cajas siguientes para asegurar que has seguido el proceso:

- [ ] He probado mi código y funciona en local
- [ ] He validado que mi código es correcto a niveles de formato
- [ ] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ ] No he copiado mi código porque soy una persona muy responsable :-)

## Opcional:

Pega una meme que exprese como te has sentido durante tu trabajo, no es obligatorio pero es divertido :-P

2023-11-16 19:58 UTC, StasKorotchenko commented
Hola @a10pepo aquí estoy esperando el review de @martinImagina

2023-11-17 08:15 UTC, martinImagina requested changes
La aplicación parece funcionar en su gran mayoría pero veo dos problemas fundamentales:

- Solo se puede ejecutar una vez --> El usuario debería poder introducir datos, buscarlos, editarlos, borrarlos y solo cuando seleccione la opción de salir, cerrar el programa. Ahora mismo tu código tiene una única ejecución y lo podrías resolver con un While que mostrara las opciones hasta que el usuario seleccione la opción de salir.

Por ejemplo, aquí se puede apreciar cómo introduzco un alumno, se muestra por consola y se cierra el programa, sin permitirme luego listar, buscar, editar o borrar:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/a4b35e4e-a1cb-468f-b211-9beab0b4403b)

Obligándome a volver a ejecutar el programa y al no persistirse la información, no poder probar las opciones de obtener todos los alumnos aprobados, por nif, borrar, etc. ya que no hay alumnos al volver a ejecutarlo.

- Otro problema o recomendación sería que está todo en un mismo archivo .py. Es decir, podrías haber separado la lógica (funciones) del archivo main.py en otros archivos y plantear módulos más fáciles de mantener :)

Por lo tanto, ahora mismo, diríamos que el programa hace casi todas las funcionalidades principales

**Otros errores y warnings de interés:**

Te comento algunos errores y warnings que no impiden que se ejecute el código, pero que deberías revisar o al menos entender las razones de su existencia:

El primero, es un error de tipos. Cuando usamos una función input('Texto para el ususario') ésta siempre va a devolver una cadena de texto (str) por lo que no podemos asignar su valor en una variable de tipo booleana:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/f0134e2d-d2a7-4df3-b03a-428dc323a034)

Dado que, además al usuario no le limitas las opciones disponibles en esta pregunta, el usuario podría poner lo que quiera, por ejemplo un "si":

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/2aab078e-9199-49d3-8494-752cc0e5171d)

y este código no funcionaría:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/3467e057-70da-4589-8394-252078171fac)

Como muestro en esta captura:

Respecto al uso de exit, deberías emplear exit(), para evitar este mensaje de warning/error:
![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/e5622cba-a9f2-47d7-be50-4437f0831385)

por lo tanto debería ser así:
![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/7c625f57-333d-412b-97b4-5f8c62694f0f)

Otro warning es el tipo de condición respecto a comparaciones. Las condiciones y comparativas "Yoda" están desaconsejadas en Python. Te comento lo que son:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/a52e0724-9f28-4a81-94e3-74a165ebc72d)

Por ello, salen Warnings como este cuando empleas este tipo de comparaciones:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/36634872-b971-489d-9560-1c1f75ec8f5a)

Deberías plantearlos así, para garantizar el estándar y eliminar el warning del IDE:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/de82f6d0-7c02-4c0c-a29f-72f37cdb2d06)

También te salen Warnings en estos otros bloques de código, que bajo la misma problemática detectada, deberías sustituir:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/22b292bf-b507-407a-a216-671455514d54)

y dejar de la siguiente manera:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/c89e96c4-f8db-4002-8f84-e66e7813ab95)

Respecto a los warning que ves en la captura anterior al final de cada línea, son sobre el tamaño máximo de línea, por lo que este no es importante... 

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/7892bb8c-5ce6-4a91-a12f-ff6176ea2ba7)

pero lo puedes corregir fácilmente, añadiendo un salto de línea entre parámetros y su correspondiente indentación:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/aec6b2eb-79a3-4fd6-adb0-701b95bf4166)

Otro warning o recomendación, es que por otro lado, las comparaciones de True y False, se recomienda usar is o is not:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/c57220a3-2b01-4a5a-ab83-a3a3a04a1096)


![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/cf24e545-76f6-4cf4-9e49-a3d620949faf)

y estos dos bloques quedar así:
![image](https://github.com/a10pepo/EDEM_MDA2324/assets/41681622/bd285289-b53d-4190-944a-40f377238fc0)


**Voy a no aprobar el programa, para que durante este fin de semana puedas tratar de hacer los cambios necesarios para queque muestre las opciones en bucle hasta que el usuario pulse la opción de salir y así, pueda probar el resto de funciones de manera funcional con los datos que vaya añadiendo, eliminando o editando . ¡Ánimo! :)**

2023-11-17 11:42 UTC, StasKorotchenko commented
Hola, Martin @martinImagina 
Muchos gracias por tus comentarios, son muy útiles y muy detallados!!!
- yo he añadido while para que el programa funcione correcto
- gracias por mejorar la calidad de código -  yo no veo en VSCode estos recomendaciónes, que yo debe añadir?
- gracias por el recomendación que mejor separar por diferentes archivos, consejo bueno, en futuro seré hacer así

2023-11-17 11:44 UTC, StasKorotchenko commented
@martinImagina  y una pregunta, por qué "Can’t automatically merge." ?
<img width="1344" alt="Снимок экрана 2023-11-17 в 12 43 52" src="https://github.com/a10pepo/EDEM_MDA2324/assets/145840814/3155ea9b-adcc-408b-8881-4ef37e5d9d42">

2023-11-17 11:58 UTC, martinImagina commented
> @martinImagina y una pregunta, por qué "Can’t automatically merge." ? <img alt="Снимок экрана 2023-11-17 в 12 43 52" width="1344" src="https://user-images.githubusercontent.com/145840814/283787512-3155ea9b-adcc-408b-8881-4ef37e5d9d42.png">

Buenas @StasKorotchenko me temo que ya no me sale la opción de aprobar después de los cambios que has realizado tras mis observaciones. Me imagino que @a10pepo te puede orientar para subirlo y que yo te lo pueda revisar y dejar aprobado :)

2023-11-21 21:05 UTC, a10pepo approved these changes

2023-11-21 21:07 UTC, a10pepo approved these changes

2023-11-21 21:09 UTC, a10pepo commented
Hola @martinImagina @StasKorotchenko este cambio no se puede mergear porque el comentario de martin es una petición de cambios:

![image](https://github.com/a10pepo/EDEM_MDA2324/assets/29485524/b1432ce9-6da7-4d98-9a65-efbc8b91f505)

Por lo que primero Martin tendría que aceptar que el cambio está bien hecho y luego se mergea. Yo lo resuelvo ;-)

2023-11-21 21:09 UTC, merged

2023-11-24 19:01 UTC, StasKorotchenko commented
@a10pepo aquí todo bien?) ✅

2024-01-18 19:33 UTC, StasKorotchenko commented
<img width="906" alt="Снимок экрана " src="https://github.com/a10pepo/EDEM_MDA2324/assets/145840814/75fdee4e-9345-4f25-94c4-61f9c877446a">
@a10pepo @martinImagina 
Buenos!
Ahora en la tabla general veo que  Python ❌, quiero preguntar que tal con esta tarea?) Antes era bien, como ✅, paro ahora no.

Hice este ejercicio mucho tiempo antes, pero no entiendo que problemas hay ahora?

2024-01-19 10:52 UTC, martinImagina commented
Buenas @StasKorotchenko por mi parte está ok con los comentarios y aprobación de los archivos que subiste. ¿será un error @a10pepo?

Si falta alguna cosa por mi parte, hacédmelo saber. ¡Saludos!

2024-01-22 15:23 UTC, a10pepo commented
Hola @StasKorotchenko  debió ser temporalmente algún error, lo tienes todo entregado sigue así!!